### ISSUE TITLE
Bug report: step function delay is reset when simulation time is edited

### ISSUE THREAD

**Issue by Felipe-noob** [miguelmoreto/labcontrole#40] opened 2023-07-02 21:31 UTC
### Steps to reproduce:

1. Create a system
2. Set initial and final values for r(t), with a delay for the step
3. plot the time response
4. Change the simulation time. It seems to occur only when typing the number, not when clicking the arrow buttons in the GUI.
5. Simulate again

### Observed result:

The delay in the step function is reset to 0 seconds.

### Expected result:

It shouldn't be changed.

### Observations:

Sometimes, this bug isn't reproduced.

**Comment by miguelmoreto** [comment] 2024-01-24 19:27
Hello @Felipe-noob. I could not reproduce this issue. Would you mind update the code in your computer and check if the but still exists?

**Comment by miguelmoreto** [comment] 2024-04-06 22:50
Closing this issue as the step time and Tmax are independent now.

**Closed by miguelmoreto** 2024-04-06 22:50 UTC
